/**
 * Static ISO-3166-1 country list with emoji flags.
 *
 * The flag emoji is derived from the 2-letter ISO code using the Regional
 * Indicator Symbol block (U+1F1E6..U+1F1FF). No images, no external deps.
 *
 * Names are provided in English and Spanish for the booking selector.
 */

export type Country = {
  /** ISO 3166-1 alpha-2 code (e.g. "MX") */
  code: string;
  /** Country name in English */
  en: string;
  /** Country name in Spanish */
  es: string;
  /** Emoji flag derived from code */
  flag: string;
};

/** Convert a 2-letter ISO code to its emoji flag. */
function toFlag(code: string): string {
  return [...code.toUpperCase()].map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65)).join('');
}

function c(code: string, en: string, es: string): Country {
  return { code, en, es, flag: toFlag(code) };
}

/**
 * Full country list sorted alphabetically by English name.
 * Ordered A-Z for the default (en) locale; the UI can re-sort for es.
 */
export const COUNTRIES: Country[] = [
  c('AF', 'Afghanistan', 'Afganistán'),
  c('AL', 'Albania', 'Albania'),
  c('DZ', 'Algeria', 'Argelia'),
  c('AD', 'Andorra', 'Andorra'),
  c('AO', 'Angola', 'Angola'),
  c('AG', 'Antigua and Barbuda', 'Antigua y Barbuda'),
  c('AR', 'Argentina', 'Argentina'),
  c('AM', 'Armenia', 'Armenia'),
  c('AU', 'Australia', 'Australia'),
  c('AT', 'Austria', 'Austria'),
  c('AZ', 'Azerbaijan', 'Azerbaiyán'),
  c('BS', 'Bahamas', 'Bahamas'),
  c('BH', 'Bahrain', 'Baréin'),
  c('BD', 'Bangladesh', 'Bangladés'),
  c('BB', 'Barbados', 'Barbados'),
  c('BY', 'Belarus', 'Bielorrusia'),
  c('BE', 'Belgium', 'Bélgica'),
  c('BZ', 'Belize', 'Belice'),
  c('BJ', 'Benin', 'Benín'),
  c('BT', 'Bhutan', 'Bután'),
  c('BO', 'Bolivia', 'Bolivia'),
  c('BA', 'Bosnia and Herzegovina', 'Bosnia y Herzegovina'),
  c('BW', 'Botswana', 'Botsuana'),
  c('BR', 'Brazil', 'Brasil'),
  c('BN', 'Brunei', 'Brunéi'),
  c('BG', 'Bulgaria', 'Bulgaria'),
  c('BF', 'Burkina Faso', 'Burkina Faso'),
  c('BI', 'Burundi', 'Burundi'),
  c('CV', 'Cabo Verde', 'Cabo Verde'),
  c('KH', 'Cambodia', 'Camboya'),
  c('CM', 'Cameroon', 'Camerún'),
  c('CA', 'Canada', 'Canadá'),
  c('CF', 'Central African Republic', 'República Centroafricana'),
  c('TD', 'Chad', 'Chad'),
  c('CL', 'Chile', 'Chile'),
  c('CN', 'China', 'China'),
  c('CO', 'Colombia', 'Colombia'),
  c('KM', 'Comoros', 'Comoras'),
  c('CG', 'Congo', 'Congo'),
  c('CD', 'Congo (DRC)', 'Congo (RDC)'),
  c('CR', 'Costa Rica', 'Costa Rica'),
  c('CI', "Côte d'Ivoire", 'Costa de Marfil'),
  c('HR', 'Croatia', 'Croacia'),
  c('CU', 'Cuba', 'Cuba'),
  c('CY', 'Cyprus', 'Chipre'),
  c('CZ', 'Czechia', 'Chequia'),
  c('DK', 'Denmark', 'Dinamarca'),
  c('DJ', 'Djibouti', 'Yibuti'),
  c('DM', 'Dominica', 'Dominica'),
  c('DO', 'Dominican Republic', 'República Dominicana'),
  c('EC', 'Ecuador', 'Ecuador'),
  c('EG', 'Egypt', 'Egipto'),
  c('SV', 'El Salvador', 'El Salvador'),
  c('GQ', 'Equatorial Guinea', 'Guinea Ecuatorial'),
  c('ER', 'Eritrea', 'Eritrea'),
  c('EE', 'Estonia', 'Estonia'),
  c('SZ', 'Eswatini', 'Esuatini'),
  c('ET', 'Ethiopia', 'Etiopía'),
  c('FJ', 'Fiji', 'Fiyi'),
  c('FI', 'Finland', 'Finlandia'),
  c('FR', 'France', 'Francia'),
  c('GA', 'Gabon', 'Gabón'),
  c('GM', 'Gambia', 'Gambia'),
  c('GE', 'Georgia', 'Georgia'),
  c('DE', 'Germany', 'Alemania'),
  c('GH', 'Ghana', 'Ghana'),
  c('GR', 'Greece', 'Grecia'),
  c('GD', 'Grenada', 'Granada'),
  c('GT', 'Guatemala', 'Guatemala'),
  c('GN', 'Guinea', 'Guinea'),
  c('GW', 'Guinea-Bissau', 'Guinea-Bisáu'),
  c('GY', 'Guyana', 'Guyana'),
  c('HT', 'Haiti', 'Haití'),
  c('HN', 'Honduras', 'Honduras'),
  c('HU', 'Hungary', 'Hungría'),
  c('IS', 'Iceland', 'Islandia'),
  c('IN', 'India', 'India'),
  c('ID', 'Indonesia', 'Indonesia'),
  c('IR', 'Iran', 'Irán'),
  c('IQ', 'Iraq', 'Irak'),
  c('IE', 'Ireland', 'Irlanda'),
  c('IL', 'Israel', 'Israel'),
  c('IT', 'Italy', 'Italia'),
  c('JM', 'Jamaica', 'Jamaica'),
  c('JP', 'Japan', 'Japón'),
  c('JO', 'Jordan', 'Jordania'),
  c('KZ', 'Kazakhstan', 'Kazajistán'),
  c('KE', 'Kenya', 'Kenia'),
  c('KI', 'Kiribati', 'Kiribati'),
  c('KP', 'North Korea', 'Corea del Norte'),
  c('KR', 'South Korea', 'Corea del Sur'),
  c('KW', 'Kuwait', 'Kuwait'),
  c('KG', 'Kyrgyzstan', 'Kirguistán'),
  c('LA', 'Laos', 'Laos'),
  c('LV', 'Latvia', 'Letonia'),
  c('LB', 'Lebanon', 'Líbano'),
  c('LS', 'Lesotho', 'Lesoto'),
  c('LR', 'Liberia', 'Liberia'),
  c('LY', 'Libya', 'Libia'),
  c('LI', 'Liechtenstein', 'Liechtenstein'),
  c('LT', 'Lithuania', 'Lituania'),
  c('LU', 'Luxembourg', 'Luxemburgo'),
  c('MG', 'Madagascar', 'Madagascar'),
  c('MW', 'Malawi', 'Malaui'),
  c('MY', 'Malaysia', 'Malasia'),
  c('MV', 'Maldives', 'Maldivas'),
  c('ML', 'Mali', 'Malí'),
  c('MT', 'Malta', 'Malta'),
  c('MH', 'Marshall Islands', 'Islas Marshall'),
  c('MR', 'Mauritania', 'Mauritania'),
  c('MU', 'Mauritius', 'Mauricio'),
  c('MX', 'Mexico', 'México'),
  c('FM', 'Micronesia', 'Micronesia'),
  c('MD', 'Moldova', 'Moldavia'),
  c('MC', 'Monaco', 'Mónaco'),
  c('MN', 'Mongolia', 'Mongolia'),
  c('ME', 'Montenegro', 'Montenegro'),
  c('MA', 'Morocco', 'Marruecos'),
  c('MZ', 'Mozambique', 'Mozambique'),
  c('MM', 'Myanmar', 'Myanmar'),
  c('NA', 'Namibia', 'Namibia'),
  c('NR', 'Nauru', 'Nauru'),
  c('NP', 'Nepal', 'Nepal'),
  c('NL', 'Netherlands', 'Países Bajos'),
  c('NZ', 'New Zealand', 'Nueva Zelanda'),
  c('NI', 'Nicaragua', 'Nicaragua'),
  c('NE', 'Niger', 'Níger'),
  c('NG', 'Nigeria', 'Nigeria'),
  c('MK', 'North Macedonia', 'Macedonia del Norte'),
  c('NO', 'Norway', 'Noruega'),
  c('OM', 'Oman', 'Omán'),
  c('PK', 'Pakistan', 'Pakistán'),
  c('PW', 'Palau', 'Palaos'),
  c('PS', 'Palestine', 'Palestina'),
  c('PA', 'Panama', 'Panamá'),
  c('PG', 'Papua New Guinea', 'Papúa Nueva Guinea'),
  c('PY', 'Paraguay', 'Paraguay'),
  c('PE', 'Peru', 'Perú'),
  c('PH', 'Philippines', 'Filipinas'),
  c('PL', 'Poland', 'Polonia'),
  c('PT', 'Portugal', 'Portugal'),
  c('PR', 'Puerto Rico', 'Puerto Rico'),
  c('QA', 'Qatar', 'Catar'),
  c('RO', 'Romania', 'Rumanía'),
  c('RU', 'Russia', 'Rusia'),
  c('RW', 'Rwanda', 'Ruanda'),
  c('KN', 'Saint Kitts and Nevis', 'San Cristóbal y Nieves'),
  c('LC', 'Saint Lucia', 'Santa Lucía'),
  c('VC', 'Saint Vincent and the Grenadines', 'San Vicente y las Granadinas'),
  c('WS', 'Samoa', 'Samoa'),
  c('SM', 'San Marino', 'San Marino'),
  c('ST', 'São Tomé and Príncipe', 'Santo Tomé y Príncipe'),
  c('SA', 'Saudi Arabia', 'Arabia Saudita'),
  c('SN', 'Senegal', 'Senegal'),
  c('RS', 'Serbia', 'Serbia'),
  c('SC', 'Seychelles', 'Seychelles'),
  c('SL', 'Sierra Leone', 'Sierra Leona'),
  c('SG', 'Singapore', 'Singapur'),
  c('SK', 'Slovakia', 'Eslovaquia'),
  c('SI', 'Slovenia', 'Eslovenia'),
  c('SB', 'Solomon Islands', 'Islas Salomón'),
  c('SO', 'Somalia', 'Somalia'),
  c('ZA', 'South Africa', 'Sudáfrica'),
  c('SS', 'South Sudan', 'Sudán del Sur'),
  c('ES', 'Spain', 'España'),
  c('LK', 'Sri Lanka', 'Sri Lanka'),
  c('SD', 'Sudan', 'Sudán'),
  c('SR', 'Suriname', 'Surinam'),
  c('SE', 'Sweden', 'Suecia'),
  c('CH', 'Switzerland', 'Suiza'),
  c('SY', 'Syria', 'Siria'),
  c('TW', 'Taiwan', 'Taiwán'),
  c('TJ', 'Tajikistan', 'Tayikistán'),
  c('TZ', 'Tanzania', 'Tanzania'),
  c('TH', 'Thailand', 'Tailandia'),
  c('TL', 'Timor-Leste', 'Timor Oriental'),
  c('TG', 'Togo', 'Togo'),
  c('TO', 'Tonga', 'Tonga'),
  c('TT', 'Trinidad and Tobago', 'Trinidad y Tobago'),
  c('TN', 'Tunisia', 'Túnez'),
  c('TR', 'Turkey', 'Turquía'),
  c('TM', 'Turkmenistan', 'Turkmenistán'),
  c('TV', 'Tuvalu', 'Tuvalu'),
  c('UG', 'Uganda', 'Uganda'),
  c('UA', 'Ukraine', 'Ucrania'),
  c('AE', 'United Arab Emirates', 'Emiratos Árabes Unidos'),
  c('GB', 'United Kingdom', 'Reino Unido'),
  c('US', 'United States', 'Estados Unidos'),
  c('UY', 'Uruguay', 'Uruguay'),
  c('UZ', 'Uzbekistan', 'Uzbekistán'),
  c('VU', 'Vanuatu', 'Vanuatu'),
  c('VA', 'Vatican City', 'Ciudad del Vaticano'),
  c('VE', 'Venezuela', 'Venezuela'),
  c('VN', 'Vietnam', 'Vietnam'),
  c('YE', 'Yemen', 'Yemen'),
  c('ZM', 'Zambia', 'Zambia'),
  c('ZW', 'Zimbabwe', 'Zimbabue'),
];

/** Lookup a country by its ISO code. */
export function getCountry(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code);
}
