import type { Media, MediaVideo } from '../../payload-types';

/**
 * Cover-render-ready output of {@link resolveMediaImage}.
 *
 * `url` carries an optional cache-bust version token, `objectPosition` is the
 * CSS `object-position` string derived from the stored focal point, and `alt`
 * is the upload's accessibility text. The triple is a plain serializable object
 * so it can cross the RSC → client boundary unchanged.
 */
export type ResolvedImage = { url: string; objectPosition: string; alt: string };

/** A Payload upload relationship: id (unhydrated), populated doc, or empty. */
export type MediaInput = number | Media | MediaVideo | null | undefined;

/** Named upload size variants generated by Payload. */
export type MediaSize = 'thumbnail' | 'card' | 'hero';

const CENTER = 50;

/** Clamp to the valid CSS percentage range and round to an integer. */
function toPercent(value: number | null | undefined): number {
  const n = value ?? CENTER;
  return Math.min(100, Math.max(0, Math.round(n)));
}

/** Pick a named size url when present, else the base url. */
function pickSizeUrl(value: Media | MediaVideo, size: MediaSize | undefined): string | null {
  if (size && 'sizes' in value) {
    const sized = value.sizes?.[size]?.url;
    if (sized) return sized;
  }
  return value.url ?? null;
}

/** Append a deterministic `?v=<epoch>` cache-bust token derived from updatedAt. */
function withVersion(url: string, updatedAt: string | null | undefined): string {
  if (!updatedAt) return url;
  const epoch = Date.parse(updatedAt);
  if (Number.isNaN(epoch)) return url;
  const separator = url.includes('?') ? '&' : '?';
  return `${url}${separator}v=${epoch}`;
}

/**
 * Resolve a Payload upload relationship into a cover-render-ready triple.
 *
 * Returns `null` for null/undefined, an unhydrated numeric id, or a populated
 * doc without a url — matching {@link resolveMediaUrl} for single-source parity.
 *
 * Pure and deterministic: same input → same output, no side effects.
 */
export function resolveMediaImage(
  value: MediaInput,
  opts?: { size?: MediaSize }
): ResolvedImage | null {
  if (!value || typeof value === 'number') return null;

  const baseUrl = pickSizeUrl(value, opts?.size);
  if (!baseUrl) return null;

  const objectPosition = `${toPercent(value.focalX)}% ${toPercent(value.focalY)}%`;

  return {
    url: withVersion(baseUrl, value.updatedAt),
    objectPosition,
    alt: value.alt ?? '',
  };
}
