/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tours: Tour;
    extras: Extra;
    bookings: Booking;
    rentals: Rental;
    'contact-messages': ContactMessage;
    users: User;
    media: Media;
    mediaVideo: MediaVideo;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tours: ToursSelect<false> | ToursSelect<true>;
    extras: ExtrasSelect<false> | ExtrasSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    rentals: RentalsSelect<false> | RentalsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    mediaVideo: MediaVideoSelect<false> | MediaVideoSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    landing: Landing;
    navigation: Navigation;
    'contact-info': ContactInfo;
    footer: Footer;
    'social-links': SocialLink;
    branding: Branding;
    'email-content': EmailContent;
    'booking-settings': BookingSetting;
  };
  globalsSelect: {
    landing: LandingSelect<false> | LandingSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'social-links': SocialLinksSelect<false> | SocialLinksSelect<true>;
    branding: BrandingSelect<false> | BrandingSelect<true>;
    'email-content': EmailContentSelect<false> | EmailContentSelect<true>;
    'booking-settings': BookingSettingsSelect<false> | BookingSettingsSelect<true>;
  };
  locale: 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: number;
  /**
   * Auto-generated from the title. Only change it if you know what you are doing — it changes the tour web address.
   */
  slug?: string | null;
  /**
   * Turn this tour into a seasonal special-event tour (cinematic hero, storytelling, gallery). Reveals seasonal-only fields below.
   */
  isSeasonal?: boolean | null;
  /**
   * The tour name as it appears across the site.
   */
  title: string;
  /**
   * Type of tour.
   */
  category: 'ebike' | 'walking' | 'daytrip' | 'food';
  /**
   * E.g. "3.5h", "4h", "8h".
   */
  duration: string;
  /**
   * E.g. "14 km". Optional — only e-bike tours typically have it.
   */
  distance?: string | null;
  /**
   * Price per person (MXN).
   */
  price: number;
  /**
   * One-liner used on cards (max 200 chars).
   */
  shortDescription: string;
  /**
   * Optional badge like "Most booked" / "Más reservado".
   */
  tag?: string | null;
  /**
   * Badge color. Optional. Matches the brand palette.
   */
  tagColor?: ('terra' | 'maya' | 'profundo' | 'crema') | null;
  /**
   * E.g. "EN · ES". Same string in both locales — non-localized.
   */
  languages?: string | null;
  /**
   * E.g. "Up to 8" / "Hasta 8".
   */
  groupSize?: string | null;
  /**
   * What the cover photo should depict (e.g. "Coyoacán plaza · golden hour"). Hint for the client choosing the first image to upload.
   */
  photoDescription?: string | null;
  /**
   * The tour photos. The first photo is the cover shown on the card and at the top of the tour page — drag to reorder.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Detail page — first paragraph.
   */
  aboutP1?: string | null;
  /**
   * Detail page — second paragraph.
   */
  aboutP2?: string | null;
  itinerary?:
    | {
        /**
         * E.g. "14:00". Same in both locales.
         */
        time: string;
        heading: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  includes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Short label, e.g. "Café Avellaneda, Coyoacán".
   */
  meetingPoint?: string | null;
  /**
   * Longer description of how to find the meeting point.
   */
  meetingPointText?: string | null;
  meetingLocation?: {
    address?: string | null;
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * Stops along the route, in order. The route map draws the road path between them. Add at least 2 to show the map.
   */
  route?:
    | {
        label?: string | null;
        lat: number;
        lng: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Days of the week this tour runs. Leave empty if the tour is paused. The site uses these to gate the booking calendar.
   */
  availableDays?: ('0' | '1' | '2' | '3' | '4' | '5' | '6')[] | null;
  /**
   * Check if this tour uses the shared e-bike fleet. Bike tours reserve bikes by capacity and need a recharge buffer between rides. Requires a duration below.
   */
  usesBikes?: boolean | null;
  /**
   * Exact ride length in minutes (e.g. 120 for 2h). Required for bike tours — used for fleet windows and the recharge buffer.
   */
  durationMinutes?: number | null;
  /**
   * Departure times the tour runs and how many seats each one has. The booking flow reads this per-tour — no global default applies anymore.
   */
  timeSlots?:
    | {
        /**
         * 24h format HH:MM (e.g. "09:00", "14:30").
         */
        time: string;
        /**
         * Maximum persons (adults + teens) bookable in this departure slot.
         */
        capacity: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Which extras a customer can add when booking this tour.
   */
  extras?: (number | Extra)[] | null;
  /**
   * Seasonal event content. Only used when "Is seasonal" is checked.
   */
  seasonal?: {
    /**
     * Display-only date of the event. Does not affect booking availability.
     */
    eventDate?: string | null;
    /**
     * Display-only season window (e.g. the days the event runs).
     */
    seasonWindow?: {
      start?: string | null;
      end?: string | null;
    };
    seasonalHero?: {
      /**
       * Choose the seasonal hero background medium.
       */
      mediaType?: ('image' | 'video') | null;
      image?: (number | null) | Media;
      /**
       * Background video (muted, looping). Mobile/reduced-motion show the poster only.
       */
      video?: (number | null) | MediaVideo;
      /**
       * Poster: first paint + mobile/reduced-motion still.
       */
      poster?: (number | null) | Media;
    };
    gallery?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Structured storytelling blocks (heading + body + optional image).
     */
    storytelling?:
      | {
          heading?: string | null;
          body?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Event location label, e.g. "Tlaxcala".
     */
    eventLocation?: string | null;
    /**
     * Short cinematic tagline shown over the hero.
     */
    tagline?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Accessibility: short description of the image content.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "extras".
 */
export interface Extra {
  id: number;
  /**
   * Customer-facing name of the extra (e.g. "Private tour").
   */
  name: string;
  title?: string | null;
  /**
   * Whole-peso MXN price. Global — applies to every tour that offers this extra.
   */
  price: number;
  /**
   * Flat = charged once regardless of headcount. Per person = price × (adults + teens).
   */
  priceType: 'total' | 'perPerson';
  /**
   * Fine print shown in the ⓘ tooltip next to the extra on the tour page.
   */
  disclaimer?: string | null;
  /**
   * Only active extras are offered in the booking wizard.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaVideo".
 */
export interface MediaVideo {
  id: number;
  /**
   * Accessibility: short description of the video content.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  /**
   * Auto-generated public booking reference.
   */
  reference: string;
  /**
   * Which tour was booked.
   */
  tour: number | Tour;
  /**
   * Local calendar date of the departure (no time component).
   */
  date: string;
  /**
   * Departure time in HH:MM. Must match one of the tour timeSlots at booking time.
   */
  time: string;
  adults: number;
  teens: number;
  /**
   * adults + teens — stored for fast capacity queries.
   */
  totalPersons: number;
  privatize?: boolean | null;
  /**
   * MXN per person at the time of booking (snapshot — not linked).
   */
  pricePerPerson: number;
  /**
   * Legacy snapshot of the old +USD 140 privatize fee. Historical bookings only — new bookings use Extras.
   */
  privatizeFee?: number | null;
  /**
   * Frozen snapshot of the extras chosen at booking time. Read-only — set by the checkout flow.
   */
  selectedExtras?:
    | {
        extraId: number;
        name: string;
        unitPrice: number;
        priceType: 'total' | 'perPerson';
        computedAmount: number;
        id?: string | null;
      }[]
    | null;
  currency: string;
  /**
   * Cached total. Stripe charges this amount.
   */
  totalAmount: number;
  customer: {
    name: string;
    email: string;
    whatsapp?: string | null;
    /**
     * ISO 3166-1 alpha-2 code (e.g. MX, US, AR).
     */
    country: string;
    locale: 'en' | 'es';
  };
  /**
   * pending: hold active; counts against capacity until holdExpiresAt. paid: confirmed; counts against capacity permanently. expired: hold expired without payment; does NOT count. cancelled: customer or admin cancelled; does NOT count. refunded: paid then refunded; does NOT count.
   */
  status: 'pending' | 'paid' | 'expired' | 'cancelled' | 'refunded';
  /**
   * When the pending hold lapses. Only meaningful while status = pending. Sub-etapa B will sweep expired holds.
   */
  holdExpiresAt?: string | null;
  /**
   * Stripe Checkout Session ID (cs_test_… in test mode). Filled when the checkout session is created in Sub-etapa C.
   */
  stripeCheckoutSessionId?: string | null;
  /**
   * Stripe PaymentIntent ID. Filled by the Stripe webhook in Sub-etapa C when payment succeeds.
   */
  stripePaymentIntentId?: string | null;
  paidAt?: string | null;
  /**
   * Internal admin notes (not sent to the customer).
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rentals".
 */
export interface Rental {
  id: number;
  /**
   * Auto-generated public rental reference.
   */
  reference: string;
  /**
   * Local calendar date of the rental (no time component).
   */
  date: string;
  /**
   * Rental start time in HH:MM (CDMX wall clock).
   */
  startTime: string;
  /**
   * Rental duration in minutes — snapshot from the chosen tier.
   */
  durationMinutes: number;
  /**
   * MXN per-bike price at rental time (snapshot from the chosen tier).
   */
  unitPrice: number;
  /**
   * How many bikes are rented.
   */
  quantity: number;
  currency: string;
  /**
   * Cached total = quantity × unit price. Stripe charges this amount.
   */
  totalAmount: number;
  customer: {
    name: string;
    email: string;
    whatsapp?: string | null;
    /**
     * ISO 3166-1 alpha-2 code (e.g. MX, US, AR).
     */
    country: string;
    locale: 'en' | 'es';
  };
  /**
   * pending: hold active; counts against the fleet until holdExpiresAt. paid: confirmed; counts permanently. expired: hold lapsed without payment; does NOT count. cancelled: cancelled; does NOT count. refunded: paid then refunded; does NOT count.
   */
  status: 'pending' | 'paid' | 'expired' | 'cancelled' | 'refunded';
  /**
   * When the pending hold lapses. Only meaningful while status = pending.
   */
  holdExpiresAt?: string | null;
  /**
   * Stripe Checkout Session ID. Filled when the checkout session is created.
   */
  stripeCheckoutSessionId?: string | null;
  /**
   * Stripe PaymentIntent ID. Filled by the Stripe webhook when payment succeeds.
   */
  stripePaymentIntentId?: string | null;
  paidAt?: string | null;
  /**
   * Internal admin notes (not sent to the customer).
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages sent through the contact form on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  /**
   * Optional — only present if the visitor left a number.
   */
  phone?: string | null;
  message: string;
  /**
   * Mark messages as you handle them.
   */
  status: 'new' | 'read' | 'replied' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tours';
        value: number | Tour;
      } | null)
    | ({
        relationTo: 'extras';
        value: number | Extra;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'rentals';
        value: number | Rental;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'mediaVideo';
        value: number | MediaVideo;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  slug?: T;
  isSeasonal?: T;
  title?: T;
  category?: T;
  duration?: T;
  distance?: T;
  price?: T;
  shortDescription?: T;
  tag?: T;
  tagColor?: T;
  languages?: T;
  groupSize?: T;
  photoDescription?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  aboutP1?: T;
  aboutP2?: T;
  itinerary?:
    | T
    | {
        time?: T;
        heading?: T;
        description?: T;
        id?: T;
      };
  includes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  meetingPoint?: T;
  meetingPointText?: T;
  meetingLocation?:
    | T
    | {
        address?: T;
        lat?: T;
        lng?: T;
      };
  route?:
    | T
    | {
        label?: T;
        lat?: T;
        lng?: T;
        id?: T;
      };
  availableDays?: T;
  usesBikes?: T;
  durationMinutes?: T;
  timeSlots?:
    | T
    | {
        time?: T;
        capacity?: T;
        id?: T;
      };
  extras?: T;
  seasonal?:
    | T
    | {
        eventDate?: T;
        seasonWindow?:
          | T
          | {
              start?: T;
              end?: T;
            };
        seasonalHero?:
          | T
          | {
              mediaType?: T;
              image?: T;
              video?: T;
              poster?: T;
            };
        gallery?:
          | T
          | {
              image?: T;
              id?: T;
            };
        storytelling?:
          | T
          | {
              heading?: T;
              body?: T;
              image?: T;
              id?: T;
            };
        eventLocation?: T;
        tagline?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "extras_select".
 */
export interface ExtrasSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  price?: T;
  priceType?: T;
  disclaimer?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  reference?: T;
  tour?: T;
  date?: T;
  time?: T;
  adults?: T;
  teens?: T;
  totalPersons?: T;
  privatize?: T;
  pricePerPerson?: T;
  privatizeFee?: T;
  selectedExtras?:
    | T
    | {
        extraId?: T;
        name?: T;
        unitPrice?: T;
        priceType?: T;
        computedAmount?: T;
        id?: T;
      };
  currency?: T;
  totalAmount?: T;
  customer?:
    | T
    | {
        name?: T;
        email?: T;
        whatsapp?: T;
        country?: T;
        locale?: T;
      };
  status?: T;
  holdExpiresAt?: T;
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  paidAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rentals_select".
 */
export interface RentalsSelect<T extends boolean = true> {
  reference?: T;
  date?: T;
  startTime?: T;
  durationMinutes?: T;
  unitPrice?: T;
  quantity?: T;
  currency?: T;
  totalAmount?: T;
  customer?:
    | T
    | {
        name?: T;
        email?: T;
        whatsapp?: T;
        country?: T;
        locale?: T;
      };
  status?: T;
  holdExpiresAt?: T;
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  paidAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaVideo_select".
 */
export interface MediaVideoSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing".
 */
export interface Landing {
  id: number;
  hero: {
    /**
     * The big primary hero heading. Shown as the main <h1>, e.g. a famous quote. Wrap text in *asterisks* to highlight it in pink, e.g. "La vida es *corta*".
     */
    quote: string;
    /**
     * Optional attribution shown under the heading, e.g. "Frida Kahlo".
     */
    quoteAuthor?: string | null;
    /**
     * Optional. Override the font of the main heading using any Google Font. Leave blank to keep the default.
     */
    headingFont?: {
      /**
       * Exact Google Fonts family name, e.g. "Playfair Display", "Oswald", "Montserrat". Copy it as written on fonts.google.com. Leave blank for the default.
       */
      family?: string | null;
      /**
       * Font weight, matching the weights shown on Google Fonts. If the chosen font lacks this weight, the closest available one is used.
       */
      weight?: ('100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900') | null;
      /**
       * Optional. Maximum heading size on large screens, in pixels (e.g. 82). It still scales down responsively on smaller screens. Leave blank for the default (82).
       */
      sizePx?: number | null;
    };
    /**
     * Optional small logo or icon shown centered at the top of the hero, above the heading. A transparent PNG or SVG looks best. Leave empty to show nothing.
     */
    logo?: (number | null) | Media;
    ctaPrimary?: string | null;
    /**
     * Where the primary button takes the visitor. Examples: "#tours" (section on the home page), "/book" (another page on your site), "https://wa.me/52...".
     */
    ctaPrimaryHref?: string | null;
    /**
     * Optional. Shown only when filled, e.g. "Rent a bike". Links to the rentals block on the home.
     */
    ctaRentals?: string | null;
    /**
     * Where the rentals button takes the visitor. Default: "#rentals-home" (the rentals block on the home).
     */
    ctaRentalsHref?: string | null;
    /**
     * Optional. Shown only when filled, e.g. "Plan your own trip". Links to the contact section.
     */
    ctaPlan?: string | null;
    /**
     * Where the plan-your-trip button takes the visitor. Default: "#contact".
     */
    ctaPlanHref?: string | null;
    /**
     * Choose the hero background medium.
     */
    mediaType?: ('image' | 'video') | null;
    heroImage?: (number | null) | Media;
    /**
     * Background video (muted, looping). Mobile/reduced-motion show the poster only.
     */
    heroVideo?: (number | null) | MediaVideo;
  };
  marquee?: {
    /**
     * Scrolling strip text, e.g. "Coyoacán · Roma Norte · Condesa · …". End with " ·" for a clean loop.
     */
    text?: string | null;
  };
  values?: {
    /**
     * Small label, e.g. "Why us".
     */
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Subheading shown to the right of the title.
     */
    sub?: string | null;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  seasonal?: {
    /**
     * Show the seasonal highlight on the landing page.
     */
    enabled?: boolean | null;
    /**
     * Small label above the highlight, e.g. "This season".
     */
    eyebrow?: string | null;
    /**
     * The seasonal tour to highlight. Must be published and marked seasonal.
     */
    featuredSeasonalTour?: (number | null) | Tour;
  };
  tours?: {
    /**
     * Small label above the tours catalog, e.g. "Choose your ride". Leave empty to use the built-in default.
     */
    eyebrow?: string | null;
    /**
     * Heading of the tours section. Leave empty to use the built-in default.
     */
    title?: string | null;
    /**
     * Short copy next to the title. Leave empty to use the built-in default.
     */
    sub?: string | null;
  };
  services?: {
    /**
     * Small label, e.g. "Beyond the tour".
     */
    eyebrow?: string | null;
    title?: string | null;
    sub?: string | null;
    /**
     * Link label on each card, e.g. "Inquire →".
     */
    inquireCta?: string | null;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  rentals?: {
    /**
     * Small label above the block, e.g. "Bike rentals".
     */
    eyebrow?: string | null;
    /**
     * Block heading, e.g. "Rather ride on your own?".
     */
    title?: string | null;
    /**
     * Short copy under the heading.
     */
    sub?: string | null;
    /**
     * Each rentable duration and its price, e.g. "1 hour" – "$150".
     */
    durations?:
      | {
          /**
           * e.g. "1 hour", "2 hours".
           */
          label: string;
          /**
           * Shown as-is, e.g. "$150". No calculation is applied.
           */
          price: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional helmet add-on label, e.g. "Helmet".
     */
    helmetLabel?: string | null;
    /**
     * Optional helmet price, shown as-is, e.g. "$30".
     */
    helmetPrice?: string | null;
    /**
     * Label on the contact button, e.g. "Reserve by WhatsApp".
     */
    ctaLabel?: string | null;
    /**
     * Where the button goes. Default "#contact" (the contact section). To send visitors to the online rental flow, use "/rent". Can also be a WhatsApp/phone link.
     */
    ctaHref?: string | null;
    /**
     * Optional photo shown next to the price list, e.g. the rental bike. If empty, a placeholder is shown.
     */
    image?: (number | null) | Media;
  };
  about?: {
    /**
     * Small label, e.g. "Our approach".
     */
    eyebrow?: string | null;
    title?: string | null;
    /**
     * First paragraph.
     */
    p1?: string | null;
    /**
     * Second paragraph.
     */
    p2?: string | null;
    /**
     * Button label, e.g. "Meet the guides →".
     */
    meetCta?: string | null;
    /**
     * Single photo, used only when the gallery below is empty. If both are empty, a placeholder is shown.
     */
    image?: (number | null) | Media;
    /**
     * Upload one or more photos. With two or more, they auto-rotate as a slider in the same image frame (no design change). Swipe or drag also works.
     */
    images?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Caption shown over the placeholder when no image is uploaded.
     */
    imageLabel?: string | null;
  };
  testimonial?: {
    /**
     * Small label, e.g. "Notes from guests".
     */
    eyebrow?: string | null;
    /**
     * Each entry is a full testimonial shown in the slider. The layout stays identical across slides.
     */
    items?:
      | {
          quote?: string | null;
          /**
           * Guest name, e.g. "Hana K.".
           */
          name?: string | null;
          /**
           * Optional location line, e.g. "Brooklyn, NY". The date is set separately below.
           */
          loc?: string | null;
          /**
           * Number of filled stars, 1 to 5. Shown as a gold star row like a Google review.
           */
          rating?: number | null;
          /**
           * Date the review was left. Auto-formatted per language, e.g. "4 May 2026".
           */
          date?: string | null;
          /**
           * Show the blue verification checkmark over the profile photo.
           */
          verified?: boolean | null;
          /**
           * Guest photo. If empty, a placeholder circle is shown.
           */
          avatar?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  faq?: {
    /**
     * Small label, e.g. "Practical".
     */
    eyebrow?: string | null;
    title?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  team?: {
    /**
     * Small label, e.g. "The people".
     */
    eyebrow?: string | null;
    /**
     * Section heading, e.g. "Our team".
     */
    title?: string | null;
    /**
     * Optional short intro under the heading.
     */
    sub?: string | null;
    /**
     * Add team members. Three look best in a row.
     */
    items?:
      | {
          /**
           * Person name, e.g. "Diego R.".
           */
          name: string;
          /**
           * Role / title, e.g. "Lead guide".
           */
          role: string;
          /**
           * Profile photo. If empty, a placeholder circle is shown.
           */
          photo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  links?:
    | {
        label: string;
        /**
         * Path or anchor (e.g. "tours", "about"). Locale prefix is added by routing.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Label for the primary "Book a tour" CTA in the nav.
   */
  bookCtaLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  /**
   * International format including country code, e.g. "+525555555555".
   */
  whatsapp?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Physical address — same in both locales.
   */
  address?: string | null;
  /**
   * Second address line, e.g. "Ciudad de México, 06700".
   */
  address2?: string | null;
  /**
   * Optional label like "Studio" / "Estudio".
   */
  addressLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Wall photo behind the footer. Until one is uploaded, the interim bundled mural displays; a dark overlay keeps the text readable.
   */
  backgroundImage?: (number | null) | Media;
  /**
   * Main tease line, e.g. "Come ride with us.".
   */
  tease?: string | null;
  /**
   * Emphasized (italic) tease, e.g. "CDMX is waiting.".
   */
  teaseEm?: string | null;
  /**
   * Optional. Override the font of the main heading using any Google Font. Leave blank to keep the default.
   */
  headingFont?: {
    /**
     * Exact Google Fonts family name, e.g. "Playfair Display", "Oswald", "Montserrat". Copy it as written on fonts.google.com. Leave blank for the default.
     */
    family?: string | null;
    /**
     * Font weight, matching the weights shown on Google Fonts. If the chosen font lacks this weight, the closest available one is used.
     */
    weight?: ('100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900') | null;
    /**
     * Optional. Maximum heading size on large screens, in pixels (e.g. 112). It still scales down responsively on smaller screens. Leave blank for the default (112).
     */
    sizePx?: number | null;
  };
  cta?: string | null;
  copyright?: string | null;
  /**
   * Coordinates shown bottom-right, e.g. "19.43°N · 99.13°W".
   */
  geoLabel?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links".
 */
export interface SocialLink {
  id: number;
  /**
   * Full profile URL.
   */
  instagram?: string | null;
  /**
   * Full profile URL.
   */
  tiktok?: string | null;
  /**
   * Full channel URL.
   */
  youtube?: string | null;
  /**
   * Full page URL.
   */
  facebook?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding".
 */
export interface Branding {
  id: number;
  /**
   * Primary logo shown in the top navigation (over light surfaces).
   */
  logoLight?: (number | null) | Media;
  /**
   * Logo used over dark surfaces such as the footer. Falls back to the primary logo.
   */
  logoDark?: (number | null) | Media;
  /**
   * Accessible alt text for the logo. Defaults to "Los Chillangos".
   */
  logoAltText?: string | null;
  /**
   * Optional logo height in pixels for the nav (default 40).
   */
  logoHeight?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Wording for the booking confirmation email sent to guests after payment. Leave a field empty to use the built-in default. Dynamic details (tour, date, time, guests, total, reference) are added automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-content".
 */
export interface EmailContent {
  id: number;
  /**
   * Optional logo for the email header. If empty, the brand name is shown.
   */
  logo?: (number | null) | Media;
  confirmation?: {
    /**
     * Email subject. Tokens: {tour}, {reference}.
     */
    subject?: string | null;
    /**
     * Inbox preview snippet shown next to the subject (~90 chars).
     */
    previewText?: string | null;
    /**
     * Greeting line. Token: {name}.
     */
    greeting?: string | null;
    /**
     * Opening paragraph under the greeting.
     */
    intro?: string | null;
    /**
     * Things to know before the tour. One item per line — shown as bullets.
     */
    goodToKnow?: string | null;
    /**
     * Optional meeting-point note. Leave empty to hide the section.
     */
    meetingPoint?: string | null;
    /**
     * Optional closing line before the signature.
     */
    closing?: string | null;
    /**
     * Sign-off line.
     */
    signature?: string | null;
    /**
     * Small print in the footer (e.g. cancellation policy).
     */
    footnote?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-settings".
 */
export interface BookingSetting {
  id: number;
  /**
   * How many days before the tour a customer can cancel for free. Shown in the booking sidebar.
   */
  freeCancellationDays: number;
  /**
   * How many bikes exist in total. Overlapping bike tours share this fleet — a slot is blocked when their combined capacity would exceed it.
   */
  totalBikes: number;
  /**
   * Minutes the bikes need to recharge after a tour ends before the next bike tour can start. Default 120 (2h).
   */
  bufferMinutes: number;
  /**
   * Duration to per-bike price options offered for standalone rentals (MXN).
   */
  rentalTiers: {
    durationMinutes: number;
    price: number;
    id?: string | null;
  }[];
  /**
   * Earliest rental start time (HH:MM, CDMX wall clock).
   */
  openTime: string;
  /**
   * Latest instant a rental ride may end (HH:MM, CDMX wall clock). Must be after open time.
   */
  closeTime: string;
  /**
   * Step between rental start blocks in the picker grid. Default 30.
   */
  rentalGranularityMinutes: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing_select".
 */
export interface LandingSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        quote?: T;
        quoteAuthor?: T;
        headingFont?:
          | T
          | {
              family?: T;
              weight?: T;
              sizePx?: T;
            };
        logo?: T;
        ctaPrimary?: T;
        ctaPrimaryHref?: T;
        ctaRentals?: T;
        ctaRentalsHref?: T;
        ctaPlan?: T;
        ctaPlanHref?: T;
        mediaType?: T;
        heroImage?: T;
        heroVideo?: T;
      };
  marquee?:
    | T
    | {
        text?: T;
      };
  values?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  seasonal?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        featuredSeasonalTour?: T;
      };
  tours?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  services?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        inquireCta?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  rentals?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        durations?:
          | T
          | {
              label?: T;
              price?: T;
              id?: T;
            };
        helmetLabel?: T;
        helmetPrice?: T;
        ctaLabel?: T;
        ctaHref?: T;
        image?: T;
      };
  about?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        p1?: T;
        p2?: T;
        meetCta?: T;
        image?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        imageLabel?: T;
      };
  testimonial?:
    | T
    | {
        eyebrow?: T;
        items?:
          | T
          | {
              quote?: T;
              name?: T;
              loc?: T;
              rating?: T;
              date?: T;
              verified?: T;
              avatar?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  team?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        items?:
          | T
          | {
              name?: T;
              role?: T;
              photo?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  bookCtaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  whatsapp?: T;
  email?: T;
  phone?: T;
  address?: T;
  address2?: T;
  addressLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  backgroundImage?: T;
  tease?: T;
  teaseEm?: T;
  headingFont?:
    | T
    | {
        family?: T;
        weight?: T;
        sizePx?: T;
      };
  cta?: T;
  copyright?: T;
  geoLabel?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  instagram?: T;
  tiktok?: T;
  youtube?: T;
  facebook?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding_select".
 */
export interface BrandingSelect<T extends boolean = true> {
  logoLight?: T;
  logoDark?: T;
  logoAltText?: T;
  logoHeight?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-content_select".
 */
export interface EmailContentSelect<T extends boolean = true> {
  logo?: T;
  confirmation?:
    | T
    | {
        subject?: T;
        previewText?: T;
        greeting?: T;
        intro?: T;
        goodToKnow?: T;
        meetingPoint?: T;
        closing?: T;
        signature?: T;
        footnote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-settings_select".
 */
export interface BookingSettingsSelect<T extends boolean = true> {
  freeCancellationDays?: T;
  totalBikes?: T;
  bufferMinutes?: T;
  rentalTiers?:
    | T
    | {
        durationMinutes?: T;
        price?: T;
        id?: T;
      };
  openTime?: T;
  closeTime?: T;
  rentalGranularityMinutes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}