/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tours: Tour;
    bookings: Booking;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tours: ToursSelect<false> | ToursSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    navigation: Navigation;
    'contact-info': ContactInfo;
    hero: Hero;
    footer: Footer;
    'social-links': SocialLink;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'social-links': SocialLinksSelect<false> | SocialLinksSelect<true>;
  };
  locale: 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Accessibility: short description of the image content.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: number;
  /**
   * URL-safe identifier (kebab-case). Same slug serves both locales.
   */
  slug: string;
  title: string;
  category: 'ebike' | 'walking' | 'daytrip' | 'food';
  /**
   * E.g. "3.5h", "4h", "8h".
   */
  duration: string;
  /**
   * E.g. "14 km". Optional — only e-bike tours typically have it.
   */
  distance?: string | null;
  /**
   * USD price per person.
   */
  price: number;
  /**
   * Optional badge like "Most booked" / "Más reservado".
   */
  tag?: string | null;
  /**
   * Badge color. Optional.
   */
  tagColor?: ('terra' | 'cloud' | 'navy' | 'forest') | null;
  /**
   * One-liner used on cards (max 200 chars).
   */
  shortDescription: string;
  /**
   * What the hero photo should depict (e.g. "Coyoacán plaza · golden hour"). Hint for the client choosing an image to upload.
   */
  photoDescription?: string | null;
  heroImage: number | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Detail page — first paragraph.
   */
  aboutP1?: string | null;
  /**
   * Detail page — second paragraph.
   */
  aboutP2?: string | null;
  /**
   * Detail page headline part A (e.g. "The classic CDMX,").
   */
  headlineA?: string | null;
  /**
   * Detail page headline part B (e.g. " on a bike.").
   */
  headlineB?: string | null;
  /**
   * Short label, e.g. "Café Avellaneda, Coyoacán".
   */
  meetingPoint?: string | null;
  /**
   * Longer description of how to find the meeting point.
   */
  meetingPointText?: string | null;
  /**
   * E.g. "Up to 8" / "Hasta 8".
   */
  groupSize?: string | null;
  /**
   * Days of the week this tour runs. Leave empty if the tour is paused. The site uses these to gate the booking calendar.
   */
  availableDays?: ('0' | '1' | '2' | '3' | '4' | '5' | '6')[] | null;
  /**
   * Departure times the tour runs and how many seats each one has. The booking flow reads this per-tour — no global default applies anymore.
   */
  timeSlots?:
    | {
        /**
         * 24h format HH:MM (e.g. "09:00", "14:30").
         */
        time: string;
        /**
         * Maximum persons (adults + teens) bookable in this departure slot.
         */
        capacity: number;
        id?: string | null;
      }[]
    | null;
  /**
   * E.g. "EN · ES". Same string in both locales — non-localized.
   */
  languages?: string | null;
  /**
   * Difficulty label, e.g. "Easy" / "Fácil".
   */
  level?: string | null;
  itinerary?:
    | {
        /**
         * E.g. "14:00". Same in both locales.
         */
        time: string;
        heading: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  includes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  /**
   * Auto-generated public booking reference.
   */
  reference: string;
  /**
   * Which tour was booked.
   */
  tour: number | Tour;
  /**
   * Local calendar date of the departure (no time component).
   */
  date: string;
  /**
   * Departure time in HH:MM. Must match one of the tour timeSlots at booking time.
   */
  time: string;
  adults: number;
  teens: number;
  /**
   * adults + teens — stored for fast capacity queries.
   */
  totalPersons: number;
  privatize?: boolean | null;
  /**
   * USD per person at the time of booking (snapshot — not linked).
   */
  pricePerPerson: number;
  /**
   * Snapshot of the privatize flat fee at booking time (matches the legacy +USD 140 constant; not enforced here).
   */
  privatizeFee: number;
  currency: string;
  /**
   * Cached total. Stripe charges this amount.
   */
  totalAmount: number;
  customer: {
    name: string;
    email: string;
    whatsapp?: string | null;
    locale: 'en' | 'es';
  };
  /**
   * pending: hold active; counts against capacity until holdExpiresAt. paid: confirmed; counts against capacity permanently. expired: hold expired without payment; does NOT count. cancelled: customer or admin cancelled; does NOT count. refunded: paid then refunded; does NOT count.
   */
  status: 'pending' | 'paid' | 'expired' | 'cancelled' | 'refunded';
  /**
   * When the pending hold lapses. Only meaningful while status = pending. Sub-etapa B will sweep expired holds.
   */
  holdExpiresAt?: string | null;
  /**
   * Stripe Checkout Session ID (cs_test_… in test mode). Filled when the checkout session is created in Sub-etapa C.
   */
  stripeCheckoutSessionId?: string | null;
  /**
   * Stripe PaymentIntent ID. Filled by the Stripe webhook in Sub-etapa C when payment succeeds.
   */
  stripePaymentIntentId?: string | null;
  paidAt?: string | null;
  /**
   * Internal admin notes (not sent to the customer).
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tours';
        value: number | Tour;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  category?: T;
  duration?: T;
  distance?: T;
  price?: T;
  tag?: T;
  tagColor?: T;
  shortDescription?: T;
  photoDescription?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  aboutP1?: T;
  aboutP2?: T;
  headlineA?: T;
  headlineB?: T;
  meetingPoint?: T;
  meetingPointText?: T;
  groupSize?: T;
  availableDays?: T;
  timeSlots?:
    | T
    | {
        time?: T;
        capacity?: T;
        id?: T;
      };
  languages?: T;
  level?: T;
  itinerary?:
    | T
    | {
        time?: T;
        heading?: T;
        description?: T;
        id?: T;
      };
  includes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  reference?: T;
  tour?: T;
  date?: T;
  time?: T;
  adults?: T;
  teens?: T;
  totalPersons?: T;
  privatize?: T;
  pricePerPerson?: T;
  privatizeFee?: T;
  currency?: T;
  totalAmount?: T;
  customer?:
    | T
    | {
        name?: T;
        email?: T;
        whatsapp?: T;
        locale?: T;
      };
  status?: T;
  holdExpiresAt?: T;
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  paidAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  links?:
    | {
        label: string;
        /**
         * Path or anchor (e.g. "tours", "about"). Locale prefix is added by routing.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Label for the primary "Book a tour" CTA in the nav.
   */
  bookCtaLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  /**
   * International format including country code, e.g. "+525555555555".
   */
  whatsapp?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Physical address — same in both locales.
   */
  address?: string | null;
  /**
   * Optional label like "Studio" / "Estudio".
   */
  addressLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  eyebrow?: string | null;
  h1a?: string | null;
  h1b?: string | null;
  h1c?: string | null;
  h1d?: string | null;
  lede?: string | null;
  ctaPrimary?: string | null;
  ctaGhost?: string | null;
  heroImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Main tease line, e.g. "Come ride with us.".
   */
  tease?: string | null;
  /**
   * Emphasized (italic) tease, e.g. "CDMX is waiting.".
   */
  teaseEm?: string | null;
  cta?: string | null;
  copyright?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links".
 */
export interface SocialLink {
  id: number;
  instagram?: string | null;
  tiktok?: string | null;
  youtube?: string | null;
  facebook?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  bookCtaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  whatsapp?: T;
  email?: T;
  phone?: T;
  address?: T;
  addressLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  eyebrow?: T;
  h1a?: T;
  h1b?: T;
  h1c?: T;
  h1d?: T;
  lede?: T;
  ctaPrimary?: T;
  ctaGhost?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tease?: T;
  teaseEm?: T;
  cta?: T;
  copyright?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  instagram?: T;
  tiktok?: T;
  youtube?: T;
  facebook?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}